# -*- coding: utf-8 -*-
"""versionchecker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wv0cNOsuAVQD_oRKE2K83SP6g_3EUARh
"""

#print user imported module version
def version_check(user_imported=True):
    import sys, inspect
    if user_imported==True:
        available_modules=[]
        na_modules=[]

        print('module name & versions imported by user')
        print('platform: {}\n'.format(sys.platform))
        module_list=set([x for x in set(sys.modules) & set(globals())] + 
                        [value.__name__ for value in globals().values() if inspect.ismodule(value)])

        for name in module_list:
            if name not in ['IPython.core.shadowns', 'builtins']:
                try: available_modules.append('{}: {}'.format(name, sys.modules[name].__version__))
                except: na_modules.append('{}'.format(name))


        print('--name & version--', *available_modules, '\n--no version--', *na_modules, sep='\n  ')

    else:
        import pprint
        #print every module(including system embedded modules) 
        available_modules=[]
        na_modules=[]
        print('--every module name & versions imported--')
        print('platform: {}\n'.format(sys.platform))
        #module_list
        for name in [x for x in sys.modules if '_' not in x and '.' not in x]:
            try: available_modules.append('{}: {}'.format(name, sys.modules[name].__version__))
            except: na_modules.append('{}'.format(name))

        available_modules.sort()
        na_modules.sort()

        pp = pprint.PrettyPrinter(width=130, compact=True)
        pp.pprint(available_modules)
        print()
        pp.pprint(na_modules)